### PR TITLE
update oras version

### PR DESCRIPTION
**Pull request by rchincha**
# Description

`zot` latest should never break this contract.

`oras` v0.16.0 works as expected, hence updating the version.

# Pipelines

_**if applicable**, please complete checklist_
- [ ] Link(s) to or screenshot(s) of successful pipeline runs and the expected result (ie. the output of `oras discover -o tree $IMAGE`)
- [*] Verify & confirm the following:
  - [*] New functionality works as expected
  - [*] No breaking changes were introduced for existing pipelines

```
$ ./oras version
Version:        0.16.0
Go version:     go1.19.2
Git commit:     d606fed4be252fd6162f63548e024451c31f3864
Git tree state: clean

$ ./notation -v
notation version 0.11.0-alpha.4

$ ./notation sign --plain-http --envelope-type cose --media-type application/vnd.docker.distribution.manifest.v2+json localhost:8080/alpine:edge
sha256:77ee9d7d39229024fd77373e079e03f3a6d384044391a0f9ae1d1f115aa38e8e

$ ./oras discover localhost:8080/alpine:edge -o tree
localhost:8080/alpine:edge

$ ./oras attach localhost:8080/alpine:edge     --artifact-type 'signature/example'      ./signature.json:application/json
Uploading b5334d78ecfc signature.json
Uploaded  b5334d78ecfc signature.json
Attached to localhost:8080/alpine@sha256:77ee9d7d39229024fd77373e079e03f3a6d384044391a0f9ae1d1f115aa38e8e
Digest: sha256:46909d1875cbe65ba8b760056d6ee337803c551f515403b89088a699ee89a309

$ ./oras discover localhost:8080/alpine:edge -o tree
localhost:8080/alpine:edge
└── signature/example
    └── sha256:46909d1875cbe65ba8b760056d6ee337803c551f515403b89088a699ee89a309
```

# Related Work Item(s)

_Link to AzDO user story. Linking to tasks is optional, but use your judgment re: what items are resolved by the PR._

### CODE REVIEW

**Comment by dtzar** [comment]
For some reason @rchincha - when we use zot registry, the microsoft sbom runs for a really long time and has errors.

**Comment by rchincha** [comment]
> For some reason @rchincha - when we use zot registry, the microsoft sbom runs for a really long time and has errors.

Let me check this also.

**Comment by rchincha** [comment]
https://github.com/microsoft/sbom-tool

https://github.com/microsoft/sbom-tool/issues/56

```
      - name: Install and Generate SBOM
        run: |
          MSFT_SBOM_VERSION=0.3.0
          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/download/v${MSFT_SBOM_VERSION}/sbom-tool-linux-x64
          chmod +x $RUNNER_TEMP/sbom-tool
          $RUNNER_TEMP/sbom-tool generate -b . -bc . -pn ${{ env.APP_NAME }} -pv ${{env.TAG}} -ps 'wabbit-networks-io' -nsb 'https://wabbitnetworks.io'
 ```

Can't really get this tool to say anything ...

```
$ ./sbom-tool-linux-x64 help
^C
$ ./sbom-tool-linux-x64 generate
^C
$ ./sbom-tool-linux-x64 --help
^C
$ ./sbom-tool-linux-x64 -h
^C
```

Does this tool assume a docker registry (non-OCI interfaces, etc)?

**Comment by dtzar** [comment]
Not sure if it assumes a docker registry.  When we use the oras one it seems to complete with no issues every time.

**Comment by rchincha** [comment]
Trying to understand what this tool is doing. It appears to be copying a bunch of DLLs here, very slowly. Let me get back to you on this as I know more.

```
$ ls -al ~/.net/sbom-tool/1+9ycjaozl5k4USZpvYrQxJGy70P3Dw\=/ | more

total 62718
drwx------ 2 rchincha ifc        0 Nov 28 21:24 .
drwx------ 3 rchincha ifc        0 Nov 28 21:24 ..
-rw-r--r-- 1 rchincha ifc   286720 Nov 28 21:24 AutoMapper.dll
-rw-r--r-- 1 rchincha ifc   225280 Nov 28 21:24 CommandLine.dll
-rw-r--r-- 1 rchincha ifc   404480 Nov 28 21:24 Docker.DotNet.dll
-rw-r--r-- 1 rchincha ifc    36352 Nov 28 21:24 DotNet.Glob.dll
-rw-r--r-- 1 rchincha ifc   920882 Nov 28 21:24 libMonoPosixHelper.so
-rw-r--r-- 1 rchincha ifc   119696 Nov 28 21:24 Microsoft.ComponentDetection.Common.dll
-rw-r--r-- 1 rchincha ifc    64912 Nov 28 21:24 Microsoft.ComponentDetection.Contracts.dll
...

```

**Pull request merged**
